[package]
name = "loop_for_while"
version = "0.1.0"
authors = ["Dings <deen.job@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
